Vagrant.configure("2") do |config|
  config.vm.box      = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.50.3"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/provision.yml"
    ansible.host_key_checking = false
    ansible.ask_vault_pass = true
  end

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
end
