# - name: Install Git
#   apt: name=git update_cache=yes state=latest

- name: Install apt-transport-https
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
     - apt-transport-https
     - python
     - python-pip
     - python-functools32