- name: Add new GPG key
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Write Docker repo destination
  copy: content="deb https://apt.dockerproject.org/repo ubuntu-trusty main" dest=/etc/apt/sources.list.d/docker.list

- name: Install docker-engine 17.05.* CE
  apt: name=docker-engine=17.05.*~ce-0~ubuntu-trusty update_cache=yes

- name: Add group rights
  command: usermod -aG docker jenkins

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    force: yes

- name: Set permissions on docker-compose binary
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755

