- include_vars: secret.yml

- name: Add new GPG key
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Write Docker repo destination
  copy: content="deb https://apt.dockerproject.org/repo ubuntu-trusty main" dest=/etc/apt/sources.list.d/docker.list

- name: Install docker-engine
  apt: name=docker-engine state=latest update_cache=yes

- name: Add group rights
  command: usermod -aG docker jenkins

- name: Install Python and Pip
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - python
    - python-pip

- name: Install missing dependency - functools32
  command: pip install functools32

- name: Install docker-compose
  command: pip install docker-compose
